-- Insert test contacts data
INSERT INTO contacts (
  first_name,
  last_name,
  name, 
  email, 
  phone, 
  company, 
  role, 
  location, 
  linkedin, 
  website, 
  status, 
  priority,
  notes,
  tags,
  score
) VALUES 
(
  'Jennifer',
  'Fleming',
  'Jennifer Fleming',
  'jennifer.fleming@techcorp.com',
  '+1 (555) 123-4567',
  'TechCorp Solutions',
  'VP of Sales',
  'San Francisco, CA',
  'linkedin.com/in/jennifer-fleming',
  'techcorp.com',
  'Qualified',
  'High',
  'Very interested in our enterprise solution. Mentioned budget approval next quarter.',
  ARRAY['Enterprise', 'Decision Maker', 'Tech'],
  92
),
(
  'David',
  'Chen',
  'David Chen',
  'david.chen@innovatelabs.io',
  '+1 (555) 987-6543',
  'InnovateLabs',
  'CTO',
  'Austin, TX',
  'linkedin.com/in/david-chen-cto',
  'innovatelabs.io',
  'In Progress',
  'Medium',
  'Technical decision maker. Needs demo of API integration capabilities.',
  ARRAY['Tech', 'Startup', 'Innovation'],
  78
),
(
  'Sarah',
  'Williams',
  'Sarah Williams',
  'sarah.williams@growthmetrics.com',
  '+1 (555) 456-7890',
  'GrowthMetrics',
  'Head of Marketing',
  'New York, NY',
  'linkedin.com/in/sarahwilliams',
  'growthmetrics.com',
  'New Contact',
  'Medium',
  'Interested in marketing automation features. Planning to evaluate Q2.',
  ARRAY['Marketing', 'B2B', 'Analytics'],
  65
),
(
  'Michael',
  'Johnson',
  'Michael Johnson',
  'michael.j@enterprisecorp.com',
  '+1 (555) 234-5678',
  'EnterpriseCorp',
  'Director of Operations',
  'Chicago, IL',
  'linkedin.com/in/michaeljohnson',
  'enterprisecorp.com',
  'Qualified',
  'High',
  'Very responsive. Scheduled for contract discussion next week.',
  ARRAY['Enterprise', 'Operations', 'Fortune 500'],
  88
);